server:
  port: 8014

spring:
  profiles:
    active: dev

  application:
    name: products

  datasource:
    url: jdbc:postgresql://${db-config.domain}/${db-config.name}
    username: ${db-config.user}
    password: ${db-config.password}
    driver-class-name: org.postgresql.Driver

  hikari:
    maximum-pool-size: 10
    minimum-idle: 1
    idle-timeout: 30000
    connection-timeout: 20000
    validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

ms-products:
  product:
    path: /api/v1/product